import { expect, test } from '@playwright/test';

test('create, connect and repair a multi-step agent in one draft', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Create new agent', exact: true }).click();
  await page.getByLabel('Message 1 instructions').fill('Welcome to the clinic.');
  await page.getByRole('button', { name: 'Agent overview', exact: true }).click();
  await page.getByLabel('Agent name', { exact: true }).fill('Manual clinic');
  await page.getByLabel('Agent instructions', { exact: true }).fill('Help the caller book a visit.');
  await page.getByRole('button', { name: 'Add step', exact: true }).click();
  await page.getByLabel('Step name').fill('insurance');
  await page.getByLabel('Step type').selectOption('end');
  await page.getByRole('form', { name: 'Add step', exact: true }).getByRole('button', { name: 'Add step', exact: true }).click();
  await page.getByLabel('Message 1 instructions').fill('Collect insurance, then say goodbye.');
  await page.getByRole('button', { name: 'Agent overview', exact: true }).click();
  await page.getByRole('button', { name: /^Start Welcome/ }).click();
  await page.getByLabel('End conversation after this step').uncheck();
  await page.getByRole('button', { name: 'Connections' }).click();
  await page.getByText('New transition', { exact: true }).click();
  await page.getByLabel('New transition condition').fill('Temporary branch');
  await page.getByLabel('New transition target').selectOption('insurance');
  await page.getByRole('button', { name: 'Add transition', exact: true }).click();
  await page.getByLabel('New transition condition').fill('Insurance collected');
  await page.getByLabel('New transition target').selectOption('insurance');
  await page.getByRole('button', { name: 'Add transition', exact: true }).click();
  await page.getByRole('region', { name: 'Transition 1', exact: true }).getByRole('button', { name: 'Delete transition' }).click();
  await page.getByText('Function details', { exact: true }).click();
  await page.getByLabel('Function name', { exact: true }).fill('record_insurance');
  await page.getByLabel('Target node', { exact: true }).selectOption('insurance');
  await page.getByLabel('Transition condition', { exact: true }).fill('After the caller gives their insurance.');
  await page.getByText('Edit collected fields', { exact: true }).click();
  await page.getByLabel('Collected fields JSON').fill(JSON.stringify({ properties: { insurance: { type: 'string', description: 'Insurance provider', native: { retained: true } } }, required: ['missing'] }));
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('main').getByRole('alert')).toContainText('undefined property');
  await page.getByLabel('Collected fields JSON').fill(JSON.stringify({ properties: { insurance: { type: 'string' } }, required: ['insurance'] }));
  await page.getByLabel('Function name', { exact: true }).fill('invalid function!');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('main').getByRole('alert')).toContainText('invalid tool name');
  await page.getByLabel('Function name', { exact: true }).fill('record_insurance');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Changes saved');
  await expect(page.getByRole('button', { name: 'Inspect start', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '→ insurance', exact: true }).click();
  await page.getByRole('button', { name: 'General', exact: true }).click();
  await page.getByRole('button', { name: 'Delete insurance', exact: true }).click();
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('main').getByRole('alert')).toContainText('no reachable call-ending');
  await page.getByRole('button', { name: /^Start Welcome/ }).click();
  await page.getByLabel('End conversation after this step').check();
  await page.getByRole('button', { name: 'Connections' }).click();
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Changes saved');
  await expect(page.getByRole('button', { name: 'Inspect insurance', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Agent overview', exact: true }).click();
  await page.getByLabel('Agent name', { exact: true }).fill('Discard me');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(page.getByLabel('Agent name', { exact: true })).toHaveValue('Manual clinic');
});

for (const width of [1440, 390]) {
  test(`graph add/delete controls and draft cancellation at ${width}`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 });
    await page.goto('/');
    if (width < 768) await page.getByRole('button', { name: 'Details', exact: true }).click();
    await page.getByRole('button', { name: 'Create new agent', exact: true }).click();
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await expect(page.getByRole('status')).toHaveText('Changes saved');
    if (width < 768) await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await page.getByRole('button', { name: 'Fit', exact: true }).click();
    await page.getByRole('button', { name: 'Add step after start', exact: true }).click();
    await page.getByLabel('Step name').fill('goodbye');
    await page.getByLabel('Step type').selectOption('end');
    await expect(page.getByRole('form', { name: 'Add step', exact: true }).getByRole('button', { name: 'Add step', exact: true })).toBeDisabled();
    await page.getByLabel('Conversation goal').fill('Thank the caller for booking and say goodbye.');
    await page.getByLabel('New transition condition').fill('The caller has no more questions.');
    await page.getByRole('form', { name: 'Add step', exact: true }).getByRole('button', { name: 'Add step', exact: true }).click();
    await page.getByRole('button', { name: 'Fit', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Delete goodbye', exact: true })).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath(`authoring-graph-${width}.png`) });
    if (width < 768) await page.getByRole('button', { name: 'Details', exact: true }).click();
    await expect(page.getByLabel('Message 1 instructions')).toHaveValue('Thank the caller for booking and say goodbye.');
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await expect(page.getByRole('status')).toHaveText('Changes saved');
    await page.getByRole('button', { name: 'Agent overview', exact: true }).click();
    if (width < 768) await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await page.getByRole('button', { name: 'Inspect goodbye', exact: true }).click();
    if (width < 768) await page.getByRole('button', { name: 'Details', exact: true }).click();
    await expect(page.getByLabel('Message 1 instructions')).toHaveValue('Thank the caller for booking and say goodbye.');
    if (width < 768) await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await page.getByRole('button', { name: 'Delete goodbye', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Inspect goodbye', exact: true })).toHaveCount(0);
    if (width < 768) await page.getByRole('button', { name: 'Details', exact: true }).click();
    await page.getByRole('button', { name: 'Cancel', exact: true }).click();
    if (width < 768) await page.getByRole('button', { name: 'Graph', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Inspect goodbye', exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Inspect transition: The caller has no more questions.', exact: true })).toBeVisible();
  });
}

for (const width of [1440, 390]) {
  test(`add step dismisses to its trigger without clearing selection at ${width}`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 });
    await page.goto('/');
    const node = page.getByRole('button', { name: 'Inspect greeting', exact: true });
    await node.click();
    const trigger = page.getByRole('button', { name: 'Add step after greeting', exact: true });
    await trigger.focus();
    await trigger.press('Enter');
    await expect(page.getByLabel('Step name')).toBeFocused();
    await page.getByLabel('Step name').fill('Insurance');
    await page.getByLabel('Conversation goal').fill('Ask for the caller’s insurance provider.');
    await page.getByLabel('New transition condition').fill('The caller is a new patient.');
    await page.screenshot({ path: testInfo.outputPath(`add-step-${width}.png`) });
    await page.getByLabel('Step name').press('Escape');
    await expect(page.getByRole('form', { name: 'Add step', exact: true })).toHaveCount(0);
    await expect(trigger).toBeFocused();
    await expect(node).toHaveAttribute('aria-pressed', 'true');
    if (width < 768) await page.getByRole('button', { name: 'Details', exact: true }).click();
    await expect(page.getByLabel('Role instructions')).not.toBeVisible();
    await page.getByText('Role instructions', { exact: false }).filter({ hasText: 'Inherited' }).click();
    await expect(page.getByLabel('Role instructions')).toBeVisible();
  });
}
